# Generated by Django 4.0.3 on 2022-03-18 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_module_professsor_module_professsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='professsor_rate',
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('module', models.ManyToManyField(to='rating.module')),
                ('professor', models.ManyToManyField(to='rating.professor')),
            ],
        ),
    ]
