# Generated by Django 4.0.3 on 2022-03-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_remove_module_professsor_rate_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='professsor',
            new_name='professor',
        ),
        migrations.AlterField(
            model_name='professor',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
