# Generated by Django 4.0.3 on 2022-03-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_rate_module_rate_professor_alter_professor_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='module',
            field=models.ForeignKey(limit_choices_to={'professor': models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rating.professor')}, on_delete=django.db.models.deletion.DO_NOTHING, to='rating.module'),
        ),
    ]
