# Generated by Django 4.0.3 on 2022-03-21 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_alter_rate_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='fromw',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rating.module'),
        ),
    ]
